### ISSUE TITLE
Make all volume controls work on the lock screen

### ISSUE THREAD

**Issue by jerryjeremiah** [seht/volumenotification#19] opened 2017-09-30 09:27 UTC
Why do some of the volume controls work on the lock screen and some do not?

For example, the ringer volume, call volume and bluetooth volume controls will pop up the slider while the phone is locked and the others won't.

If it works for some of them shouldn't it work for all of them?  I would love to be able to change them while the phone is locked.

**Comment by jerryjeremiah** [comment] 2017-09-30 09:28
I guess I should have said that I am using it on a Samsung Note 3

**Comment by jise** [comment] 2017-09-30 11:48
I guess that Samsung's customized Android version on your device is a culprit. BTW which Android version do you have?
On my LG G Flex 2 with Android 6.0.1 all seven volume controls works as it should even when the phone is locked.

**Comment by jerryjeremiah** [comment] 2017-10-01 06:00
My Android version is 5.0

**Comment by seht** [comment] 2019-08-19 20:07
I'm not able to reproduce this. Would you please clarify in what instances this happens?

**Comment by seht** [comment] 2019-08-22 15:31
Closing after deploying the first stable release. Enjoy 1.0.1 :-)

**Closed by seht** 2019-08-22 15:31 UTC
Labels: question
